import React from 'react';
export default [
  {
    url: 'https://api.github.com/repos/Canner/vulcan-sql/issues/138',
    html_url: 'https://github.com/Canner/vulcan-sql/issues/138',
    title: '[Feature Request] ClickHouse support',
    user: {
      login: 'Slach',
      avatar_url: 'https://avatars.githubusercontent.com/u/105560?v=4',
    },
    updated_at: '2023-06-21T10:09:02Z',
    content: (
      <>
        What’s the problem you're trying to solve:
        <br />
        ClickHouse blazing fast analytics database <br />I would like to support
        easy analytics API create with our great project
        <br />
        Describe the solution you’d like:
        https://clickhouse.com/docs/en/integrations/language-clients/nodejs
      </>
    ),
    emojis: {
      thumbsUp: 19,
      heart: 20,
      rocket: 6,
    },
  },
  {
    url: 'https://api.github.com/repos/Canner/vulcan-sql/pulls/160',
    html_url: 'https://github.com/Canner/vulcan-sql/pull/160',
    title: 'Feature: Support Catalog User Interface',
    user: {
      login: 'andreashimin',
      avatar_url: 'https://avatars.githubusercontent.com/u/9657305?v=4',
    },
    updated_at: '2023-05-18T06:41:10Z',
    content: (
      <>
        Description:
        <br />
        Support the VulcanSQL Catalog user interface for retrieving data in a
        more efficient and user-friendly manner.
        <br />
        For vulcan.yaml, Please notice auth options should be either basic or
        password-file is setting up or disabled the auth
        <br />
        For Catalog Server, Run Develop Command - 'yarn nx serve catalog-server'
        and open http://localhost:4200
      </>
    ),
    emojis: {
      thumbsUp: 5,
      laugh: 2,
      hooray: 2,
      heart: 4,
      rocket: 3,
    },
  },
  {
    url: 'https://api.github.com/repos/Canner/vulcan-sql/pulls/163',
    html_url: 'https://github.com/Canner/vulcan-sql/pull/163',
    title: 'Feature: implement snowflake export function #156',
    user: {
      login: 'onlyjackfrost',
      avatar_url: 'https://avatars.githubusercontent.com/u/38731840?v=4',
    },
    updated_at: '2023-05-04T04:23:37Z',
    content: (
      <>
        This pull request implemented the snowflake export function to export
        the selected data to the local dir in parquet format. <br />
        export flow:
        <br />
        ．Use the snowflake "COPY INTO..." command to convert the selected data
        into parquet format and stored in the user stage. This request will have
        a UUID generated by Snowflake, we will append this unique id to the
        stage file name to prevent concurrent copy requests with the same name
        which Snowflake will throw an error.
        <br />
        ．Use the snowflake "GET ..." command to download the parquet file
        stored in the user stage to the local directory. We Use the "pattern"
        parameter in this command and filter out the file with the unique id.
        <br />
        ．Use the snowflake "Remove ..." command to remove the parquet file in
        the user stage to avoid increasing costs. We Use the "pattern" parameter
        in this command and filter out the file with the unique id.
      </>
    ),
    emojis: {
      thumbsUp: 5,
      rocket: 5,
      heart: 2,
    },
  },
  {
    url: 'https://api.github.com/repos/Canner/vulcan-sql/issues/143',
    html_url: 'https://github.com/Canner/vulcan-sql/issues/143',
    title: 'Bigquery connection failing',
    user: {
      login: 'Navrooz',
      avatar_url: 'https://avatars.githubusercontent.com/u/4967042?v=4',
    },
    updated_at: '2023-02-22T03:12:52Z',
    content: (
      <>
        I have been trying to connect VulcanSQL with BigQuery but receive an
        error 'Not found'.
        <br />
        Also, not getting any endpoints in /localhost/doc
        <br />
        The credentials file is working fine as I tested the connection with
        DBeaver.
        <br />
        profiles, vulcan, sql and yaml files are at the below link.
        <br />
        Files:
        https://drive.google.com/drive/folders/1g1lyEG32x63hAzrIo2JK8vFAk5GpNC1U?usp=sharing
      </>
    ),
    emojis: {
      thumbsUp: 4,
      heart: 2,
    },
  },
  {
    url: 'https://api.github.com/repos/Canner/vulcan-sql/pulls/140',
    html_url: 'https://github.com/Canner/vulcan-sql/pull/140',
    title: 'Feature: Dynamic data masking - custom string',
    user: {
      login: 'fredalai',
      avatar_url: 'https://avatars.githubusercontent.com/u/42527625?v=4',
    },
    updated_at: '2023-01-17T03:15:47Z',
    content: (
      <>
        We can generate different queries depending on the user attribute, so it
        is easy to mask some columns manually
        <br />
        But manually masking each column might be annoying and unpredictable, we
        should provide "masking" tag with some masking functions.
      </>
    ),
    emojis: {
      laugh: 2,
      heart: 4,
      rocket: 3,
    },
  },
  {
    url: 'https://api.github.com/repos/Canner/vulcan-sql/pulls/131',
    html_url: 'https://github.com/Canner/vulcan-sql/pull/131',
    title: 'Feature: BigQuery support - statement',
    user: {
      login: 'JSYOU',
      avatar_url: 'https://avatars.githubusercontent.com/u/19495220?v=4',
    },
    updated_at: '2022-11-03T06:05:41Z',
    content: (
      <>
        BigQuery is one of the most commonly used warehouses, we should add
        driver support.
        <br />
        Add BigQuery data source and update the document.
      </>
    ),
    emojis: {
      thumbsUp: 4,
      laugh: 2,
      rocket: 4,
      eyes: 3,
    },
  },
];
