import React from 'react';
import axios from 'axios';
import dayjs from 'dayjs';
import clsx from 'clsx';
import Link from '@docusaurus/Link';
import styles from './styles.module.css';

import relativeTime from 'dayjs/plugin/relativeTime.js';
import Carousel from '../share/Carousel';
dayjs.extend(relativeTime);

const Discord = require('@site/static/img/discord.svg').default;
const GitHub = require('@site/static/img/github.svg').default;

enum EmojisType {
  Eyes = 'eyes',
  Heart = 'heart',
  Hooray = 'hooray',
  Laugh = 'laugh',
  Rocket = 'rocket',
  Thumbs_Up = 'thumbsUp',
}

const emojiImgSrc = (emoji: string) => {
  switch (emoji) {
    case EmojisType.Eyes:
      return './img/eyes.png';

    case EmojisType.Heart:
      return './img/heart.png';

    case EmojisType.Hooray:
      return './img/hooray.png';

    case EmojisType.Laugh:
      return './img/laugh.png';

    case EmojisType.Rocket:
      return './img/rocket.png';

    case EmojisType.Thumbs_Up:
      return './img/thumbs_up.png';
  }
};

interface GitHubIssueItem {
  content: any;
  html_url: string;
  title: string;
  updated_at: string;
  url: string;
  user: {
    avatar_url: string;
    login: string;
  };
  emojis: Record<string, number>;
}

const GITHUB_MAPPING_DATA = {
  'issues/138': {
    content: (
      <>
        What’s the problem you're trying to solve:
        <br />
        ClickHouse blazing fast analytics database <br />I would like to support
        easy analytics API create with our great project
        <br />
        Describe the solution you’d like:
        https://clickhouse.com/docs/en/integrations/language-clients/nodejs
      </>
    ),
    emojis: {
      thumbsUp: 19,
      heart: 20,
      rocket: 6,
    },
  },
  'pulls/160': {
    content: (
      <>
        Description:
        <br />
        Support the VulcanSQL Catalog user interface for retrieving data in a
        more efficient and user-friendly manner.
        <br />
        For vulcan.yaml, Please notice auth options should be either basic or
        password-file is setting up or disabled the auth
        <br />
        For Catalog Server, Run Develop Command - 'yarn nx serve catalog-server'
        and open http://localhost:4200
      </>
    ),
    emojis: {
      thumbsUp: 5,
      laugh: 2,
      hooray: 2,
      heart: 4,
      rocket: 3,
    },
  },
  'pulls/163': {
    content: (
      <>
        This pull request implemented the snowflake export function to export
        the selected data to the local dir in parquet format. <br />
        export flow:
        <br />
        ．Use the snowflake "COPY INTO..." command to convert the selected data
        into parquet format and stored in the user stage. This request will have
        a UUID generated by Snowflake, we will append this unique id to the
        stage file name to prevent concurrent copy requests with the same name
        which Snowflake will throw an error.
        <br />
        ．Use the snowflake "GET ..." command to download the parquet file
        stored in the user stage to the local directory. We Use the "pattern"
        parameter in this command and filter out the file with the unique id.
        <br />
        ．Use the snowflake "Remove ..." command to remove the parquet file in
        the user stage to avoid increasing costs. We Use the "pattern" parameter
        in this command and filter out the file with the unique id.
      </>
    ),
    emojis: {
      thumbsUp: 5,
      rocket: 5,
      heart: 2,
    },
  },
  'issues/143': {
    content: (
      <>
        I have been trying to connect VulcanSQL with BigQuery but receive an
        error 'Not found'.
        <br />
        Also, not getting any endpoints in /localhost/doc
        <br />
        The credentials file is working fine as I tested the connection with
        DBeaver.
        <br />
        profiles, vulcan, sql and yaml files are at the below link.
        <br />
        Files:
        https://drive.google.com/drive/folders/1g1lyEG32x63hAzrIo2JK8vFAk5GpNC1U?usp=sharing
      </>
    ),
    emojis: {
      thumbsUp: 4,
      heart: 2,
    },
  },
  'pulls/140': {
    content: (
      <>
        We can generate different queries depending on the user attribute, so it
        is easy to mask some columns manually
        <br />
        But manually masking each column might be annoying and unpredictable, we
        should provide "masking" tag with some masking functions.
      </>
    ),
    emojis: {
      laugh: 2,
      heart: 4,
      rocket: 3,
    },
  },
  'pulls/131': {
    content: (
      <>
        BigQuery is one of the most commonly used warehouses, we should add
        driver support.
        <br />
        Add BigQuery data source and update the document.
      </>
    ),
    emojis: {
      thumbsUp: 4,
      laugh: 2,
      rocket: 4,
      eyes: 3,
    },
  },
};

function GitHubCard({
  content,
  html_url,
  title,
  updated_at,
  user: { avatar_url: avatarUrl, login: uid },
  emojis,
}: GitHubIssueItem): JSX.Element {
  return (
    <div className={`col col--4 ${styles.gitHubCard}`}>
      <Link className={styles.cardMeta} to={html_url}>
        <div className={clsx('card', styles.cardBlock)}>
          <div className={`${styles.cardAvatarBlock}`}>
            <img
              alt={uid}
              className={`avatar__photo ${styles.cardAvatar}`}
              src={avatarUrl}
              loading="lazy"
            />
            <div className={clsx('avatar__intro', styles.cardMeta)}>
              <strong className="avatar__name">{uid}</strong>
              <span>{dayjs(updated_at).fromNow()}</span>
            </div>
            <img
              src="./img/github-icon.png"
              className={`avatar__photo ${styles.gitHubIcon}`}
              alt="GitHub Icon"
            />
          </div>
          <div className={styles.cardContent}>
            <div className={styles.gitHubTitle}>
              <strong>{title}</strong>
            </div>
            <div className={styles.gitHubContent}>
              <p>{content}</p>
            </div>
            <div className={styles.gitHubEmojis}>
              {Object.keys(emojis).map((emoji) => (
                <div key={emoji} className={styles.gitHubEmoji}>
                  <img key={emoji} src={emojiImgSrc(emoji)} alt={emoji} />
                  <span>{emojis[emoji]}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </Link>
    </div>
  );
}

function GitHubSection({ data: gitHubIssueColumns }) {
  return (
    <div className={clsx(styles.githubSection)}>
      <Carousel>
        {gitHubIssueColumns.map((item: GitHubIssueItem) => (
          <GitHubCard {...item} key={item.url} />
        ))}
      </Carousel>
    </div>
  );
}

export default function Community(): JSX.Element {
  const [data, setData] = React.useState([]);

  React.useEffect(() => {
    const fetchGitHubData = async () => {
      const data = await Promise.all(
        Object.keys(GITHUB_MAPPING_DATA).map(async (item) => {
          const { content, emojis } = GITHUB_MAPPING_DATA[item];
          try {
            const response = await axios.get(
              `https://api.github.com/repos/Canner/vulcan-sql/${item}`
            );
            return {
              ...response.data,
              content,
              emojis,
            };
          } catch (error) {
            return { item, error };
          }
        })
      );
      setData(data);
    };

    fetchGitHubData();
  }, []);

  return (
    <section className={styles.communitySection}>
      <h1 className={`text--center ${styles.title}`}>Join the Community</h1>
      <div className={`text--center ${styles.descriptionBlock}`}>
        <div className={`text--center ${styles.description}`}>
          Join the discord group to chat with the developers and directly
          connect with the VulcanSQL team.
        </div>
        <div className={`buttons ${styles.buttonContainer}`}>
          <Link
            className={`button button--outline ${styles.actionButton}`}
            to="https://discord.gg/ztDz8DCmG4"
          >
            <Discord className={styles.actionIcon} role="img" />
            Discord
          </Link>
          <Link
            className={`button button--outline ${styles.actionButton}`}
            to="https://github.com/Canner/vulcan-sql"
          >
            <GitHub className={styles.actionIcon} role="img" />
            GitHub
          </Link>
        </div>
      </div>
      <GitHubSection data={data} />
    </section>
  );
}
