import type { ColumnsType } from 'antd/es/table';
import { JOIN_TYPE } from '@vulcan-sql/admin-ui/utils/enum';
import { ModelIcon } from '@vulcan-sql/admin-ui/utils/icons';
import SelectionTable from '@vulcan-sql/admin-ui/components/table/SelectionTable';

interface ModelField {
  model: string;
  field: string;
}

export interface SourceTableColumn {
  name: string;
  type: string;
}

export interface SourceTable {
  id: string;
  sqlName: string;
  displayName: string;
  columns: SourceTableColumn[];
}

export interface RelationsDataType {
  fromField: ModelField;
  isAutoGenerated: boolean;
  relationName: string;
  relationType: JOIN_TYPE;
  toField: ModelField;
}

interface Props {
  columns: ColumnsType<RelationsDataType> | ColumnsType<SourceTableColumn>;
  dataSource: RelationsDataType[] | SourceTableColumn[];
  enableRowSelection?: boolean;
  extra?: (
    onCollapseOpen: (
      event: React.MouseEvent<HTMLElement, MouseEvent>,
      key: string
    ) => void
  ) => React.ReactNode;
  onChange?: (value: any | null) => void;
  tableTitle: string;
  rowKey: (record: RelationsDataType | SourceTableColumn) => string;
}

export default function ModelRelationSelectionTable(props: Props) {
  return (
    <SelectionTable
      {...props}
      tableHeader={
        <>
          <ModelIcon className="pr-2 text-md" />
          {props.tableTitle}
        </>
      }
    />
  );
}
